install:
    cmd: dotnet restore .\Salesforce.Chatter
    cmd: dotnet restore .\Salesforce.Chatter.UnitTests
    cmd: dotnet restore .\Salesforce.Common
    cmd: dotnet restore .\Salesforce.Common.UnitTests
    cmd: dotnet restore .\Salesforce.Force
    cmd: dotnet restore .\Salesforce.Force.UnitTests

build_script:
    cmd: dotnet build -c Release .\Salesforce.Chatter
    cmd: dotnet build -c Release .\Salesforce.Chatter.UnitTests
    cmd: dotnet build -c Release .\Salesforce.Common
    cmd: dotnet build -c Release .\Salesforce.Common.UnitTests
    cmd: dotnet build -c Release .\Salesforce.Force
    cmd: dotnet build -c Release .\Salesforce.Force.UnitTests

test_script:
    cmd: dotnet test .\Salesforce.Chatter.UnitTests
    cmd: dotnet test .\Salesforce.Common.UnitTests
    cmd: dotnet test .\Salesforce.Force.UnitTests

before_deploy:
    cmd: dotnet pack -c Release -o . .\Salesforce.Chatter
    cmd: dotnet pack -c Release -o . .\Salesforce.Common
    cmd: dotnet pack -c Release -o . .\Salesforce.Force

deploy_script:
    cmd: nuget push .\Salesforce.Chatter.1.0.0.nupkg %MYGET_TOKEN% -Source https://www.myget.org/F/sureshot-private/api/v2/package
    cmd: nuget push .\Salesforce.Common.1.0.0.nupkg %MYGET_TOKEN% -Source https://www.myget.org/F/sureshot-private/api/v2/package
    cmd: nuget push .\Salesforce.Force.1.0.0.nupkg %MYGET_TOKEN% -Source https://www.myget.org/F/sureshot-private/api/v2/package